export enum MCLogModule {
  MCTcpSocketServer = 'MCTcpSocketServer',
  MCHttpConnectionHandler = 'MCHttpConnectionHandler',
  MCHttpRequest = 'MCHttpRequest',
  MCHttpResponse = 'MCHttpResponse',
  MCMedia = 'MCMedia',
  MCMediaContent = 'MCMediaContent',
  MCMediaContentLoader = 'MCMediaContentLoader',
  MCMediaDataFetcher = 'MCMediaDataFetcher',
  MCMediaDataReader = 'MCMediaDataReader',
  MCAssetReader = 'MCAssetReader',
}