export enum MCLogModule {
  MCTcpSocketServer = 'MCTcpSocketServer',
  MCHttpConnectionHandler = 'MCHttpConnectionHandler',
  MCHttpRequest = 'MCHttpRequest',
  MCHttpResponse = 'MCHttpResponse',
  MCMedia = 'MCMedia',
  MCMediaContent = 'MCMediaContent',
  MCMediaContentLoader = 'MCMediaContentLoader',
  MCMediaDataFetcher = 'MCMediaDataFetcher',
  MCAssetDataFetcher = 'MCAssetDataFetcher',
  MCAssetAccess = 'MCAssetAccess',
  MCAssetState = 'MCAssetState',
  MCAssetCacheManager = 'MCAssetCacheManager',
}